### PR TITLE
Added button components

### PR DESCRIPTION
**Pull request by jeetsdev**
### - Solid buttons 
These buttons comes with a background color.
- Primary button 
- Secondary button
- Icon button 
- Float button
- Link button
### - Outline buttons
These buttons comes with no background color.
- Primary button 
- Secondary button
- Icon button 
- Float button

### CODE REVIEW

**Comment by jeetsdev** [comment]
https://www.loom.com/share/6fbd44c127444d83a6c6970afcdc1cbd

**Review by mohammadkhizerkhan — APPROVED** [review]
looks good to me

**Review by znjs — APPROVED** [review]

**Review by SK02K1 — CHANGES_REQUESTED** [review]
add cursor pointer to buttons

**Comment by jeetsdev** [comment]
> add cursor pointer to buttons
Thanks a lot, buddy.

**Review by SK02K1 — APPROVED** [review]

**Pull request merged**
